name: Sync Starred Repos to Codeberg

on:
  schedule:
    # 每天凌晨3点运行（UTC时间）
    - cron: '0 3 * * *'
  # 支持手动触发
  workflow_dispatch:
    inputs:
      full_sync:
        description: '强制完整同步（跳过增量检查）'
        required: false
        default: false
        type: boolean

jobs:
  sync-repos:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout sync script
      uses: actions/checkout@v4
      with:
        path: scripts
        sparse-checkout: |
          .github/scripts/sync-starred-to-codeberg.py
        sparse-checkout-cone-mode: false
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pyyaml
        
    - name: Run sync script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CODEBERG_USERNAME: ${{ secrets.CODEBERG_USERNAME }}
        CODEBERG_TOKEN: ${{ secrets.CODEBERG_TOKEN }}
        FULL_SYNC: ${{ inputs.full_sync }}
      run: |
        cd scripts
        python .github/scripts/sync-starred-to-codeberg.py
        
    - name: Upload logs (on failure)
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: sync-logs
        path: |
          sync_*.log
          sync_stats.json
        retention-days: 7